name: Docker

on:
  release:
    types: [released, prereleased]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: docker build -t ghcr.io/hyperledger/firefly-sandbox:${GITHUB_REF##*/} .

      - name: Tag release
        if: github.event.action == 'released'
        run: docker tag ghcr.io/hyperledger/firefly-sandbox:${GITHUB_REF##*/} ghcr.io/hyperledger/firefly-sandbox:latest

      - name: Push docker image
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/hyperledger/firefly-sandbox:${GITHUB_REF##*/}

      - name: Push latest tag
        if: github.event.action == 'released'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker push ghcr.io/hyperledger/firefly-sandbox:latest
