name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "v20.11.1"
      - run: npm ci
        working-directory: ./server
      - run: npm run test
        working-directory: ./server
      - run: npm ci
        working-directory: ./ui
      - run: npm run lint
        working-directory: ./ui
      - run: npm run test
        working-directory: ./ui
      - run: npm run build
        working-directory: ./ui
